spring.application.name=pushpendra

spring.datasource.url=jdbc:postgresql://localhost:5432/my_portfolio
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always

spring.thymeleaf.cache=false
logging.level.org.thymeleaf=DEBUG


# SMTP Mail Configuration (for Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singhpushpendra9326@gmail.com
spring.mail.password=nbtu srga znjy didw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:8080

# Allow file upload up to 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Portfolio website - local development
file.upload-dir=D:/uploads/profile/

#Path for the certifications
file.upload-dir-certificates=D:/uploads/certificates

#Path for the project
file.upload-dir-project=D:/uploads/project

# Production (external folder recommended, comment this)
# file.upload-dir=/var/www/portfolio/uploads/images/











